### ISSUE TITLE
Unable to import psycopg2 error in brew install.

### ISSUE THREAD

**Issue by bbengfort** [Alexis-benoist/eralchemy#11]
I installed eralchemy using brew, but when I attempt to run it, I'm getting the following error:

```
$ eralchemy -i 'postgresql+psycopg2://dakota@localhost:5432/logbook' -o logbook.pdf
Please install psycopg2 using "pip install psycopg2".
```

So for the sake of not reporting an obvious issue; I went ahead and ran the command as requested:

```
$ pip install psycopg2
Requirement already satisfied (use --upgrade to upgrade): psycopg2 in /usr/local/lib/python2.7/site-packages
```

And of course, opening a Python terminal and importing psycopg2 works. I even tried creating a virtual environment, installing pscyopg2 there, and running eralchemy. No joy. 

ERAlchemy is working for me now; I uninstalled the brew installation and used pip to install the latest and am now good to go. Not sure if anyone else has had this issue; and I don't really know how to resolve it.

**Comment by Alexis-benoist** [comment]
You are right.
We need to add psycopg to the brew install script and PR homebrew.
Le 11 févr. 2016 03:37, "Benjamin Bengfort" <notifications@github.com> a
écrit :

**Comment by bbengfort** [comment]
@Alexis-benoist ok - that makes sense. I don't have time to take a look at it at the moment; and I haven't done much with the brew install script -- but I may try to take a crack at it later.

**Comment by Alexis-benoist** [comment]
https://github.com/Homebrew/homebrew/pull/50619
