### ISSUE TITLE
Anyone know Python and OSX can help here?

### ISSUE THREAD

**Issue by resistorsoftware** [Alexis-benoist/eralchemy#22]
**pip install psycopg2**
Requirement already satisfied (use --upgrade to upgrade): psycopg2 in /usr/local/lib/python2.7/site-packages

eralchemy -i 'postgresql+psycopg2://localhost:5432/assembler_development' -s public -o foobaz.er

**Please install psycopg2 using "pip install psycopg2".**

So what is the magic Python people? How does this ancient incantation language work?

**Comment by Alexis-benoist** [comment]
How did you install ERAlchemy?

**Comment by resistorsoftware** [comment]
brew install eralchemy

**Comment by Alexis-benoist** [comment]
I should remove or fix this formula.
Just do `brew uninstall eralchemy` and install it with `pip install eralchemy`.

**Comment by resistorsoftware** [comment]
**pip install eralchemy**

Requirement already satisfied (use --upgrade to upgrade): eralchemy in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): SQLAlchemy in /usr/local/lib/python2.7/site-packages (from eralchemy)
Requirement already satisfied (use --upgrade to upgrade): pygraphviz in /usr/local/lib/python2.7/site-packages (from eralchemy)

**Comment by Alexis-benoist** [comment]
Did you do `brew uninstall eralchemy && pip install eralchemy`

**Comment by resistorsoftware** [comment]
**Yes**

Problem is, apparently, this PIP business has no ability to set paths or anything? So now when I attempt to use this code, which is installed, I get the command not found? 

Without getting into this too deep, is Python usually this hard to setup on OSX? It usually just works with *nix... but since I stopped using that, and moved to OSX, I guess I have been spoiled by homebrew

**Comment by Alexis-benoist** [comment]
pip can do that! I never had any trouble with that.

I let it open, in case someone has the same problem.

**Comment by resistorsoftware** [comment]
I used Brew to install Python. I suppose that is the root of the problem? PIP works from the command line, so why didn't the installer figure packages might be useful too. I will blow away this whole Python install and try again...

**Comment by resistorsoftware** [comment]
The solution was when I noticed the /usr/local/bin was devoid of eralchemy. I used pip to reinstall with the -I flag which forced the re-installation of the already installed code, and this time it managed to land an executable in /usr/local/bin. That was the ticket.
