### ISSUE TITLE
Restrict to tables

### ISSUE THREAD

**Issue by rornor** [Alexis-benoist/eralchemy#23]
Hi,

I'm trying to generate graph for several tables out of large db model.
Is there anyway to specify table/model names to eralchemy renderer?
I'm asking basically if I can restricts graph without using `exclude`, when I want to graph just several tables outside large db?

Thanks

**Comment by Alexis-benoist** [comment]
You want to be able to specify all the tables to include?

**Comment by rornor** [comment]
Yes, I'd like to specify for example just 4 tables, instead excluding all tables - 4
