### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by dahlia** [Alexis-benoist/eralchemy#3]
It would be great if it also works on Python 3.  FYI pygraphviz 1.3rc2 currently supports Python 3.

**Comment by Alexis-benoist** [comment]
Cool for the pygraphiz python support !
I will work on it.

**Comment by Alexis-benoist** [comment]
pygraphiz seems still wet, I think the module is ready for python3.
I still need to use and I will wait for pygraphiz to make a release to make it officially python 3 compatible.

**Comment by Alexis-benoist** [comment]
The test is big long.
The tests are passing on python 3: https://travis-ci.org/Alexis-benoist/eralchemy!
I just need to change the requirements when PyGraphviz will have updated.

**Comment by item4** [comment]
+1

**Comment by Alexis-benoist** [comment]
Tests are passing for python 3. I'm just waiting for PyGraphviz to update on PyPi.
If you need it for python 3, you can checkout the code from the repo.

**Comment by dahlia** [comment]
It seems to work well.  Thanks!

**Comment by Alexis-benoist** [comment]
Yes but can't put the flag python 3, because pygraphviz is not released yet
:(
