### ISSUE TITLE
CI fails with PostgreSQL 10

### ISSUE THREAD

**Issue by momijiame** [Alexis-benoist/eralchemy#35]
I looked into the error with my PR (#34) failure.
https://travis-ci.org/Alexis-benoist/eralchemy/jobs/322844083

It seems psycopg2 2.6.1 does not support to PostgreSQL 10.
IMHO, Therefore we should upgrade the version to use in testing.

**Comment by Alexis-benoist** [comment]
That seems to be a good idea!
Do you want to do it?

**Comment by momijiame** [comment]
Yes, I think it is better. I made PR #35 for to fix this issue.
(However, there is another problem and the test has failed partly yet)

**Comment by Alexis-benoist** [comment]
Thanks!
Do you want to be a maintainer of the project?

**Comment by momijiame** [comment]
I probably not be able to contribute much.
But if you feel okay, I will do it.

**Comment by Alexis-benoist** [comment]
That would be great !
