### ISSUE TITLE
CI fails with Python 3.3, 3.5, 3.6

### ISSUE THREAD

**Issue by momijiame** [Alexis-benoist/eralchemy#37]
My PR (#36) fixed an issue with PostgreSQL 10.
But the test still fails partly yet.
https://travis-ci.org/Alexis-benoist/eralchemy/builds/322863346?utm_source=github_status&utm_medium=notification

It seems travis environment have no Python 3.3, 3.5 and 3.6 processors.
Maybe, we should add 'python' section to travis.yml.
https://docs.travis-ci.com/user/languages/python/

**Comment by momijiame** [comment]
I noticed a branch to fix was made. Perfect!
https://github.com/Alexis-benoist/eralchemy/tree/fix_travis_python

**Comment by Alexis-benoist** [comment]
Just did it :)

2017-12-29 13:46 GMT+01:00 momijiame <notifications@github.com>:
