### ISSUE TITLE
Specify multiple schemas 

### ISSUE THREAD

**Issue by ghost** [Alexis-benoist/eralchemy#59]
Since tables can be in different schemas within the same database, it would be nice if we could show the tables across multiple schemas.

Currently this just seems to take the last specified schema, `c`.
```
eralchemy -i postgresql:///dbname -o er.pdf -s a -s b -s c
```

**Comment by maurerle** [comment]
See https://github.com/maurerle/eralchemy2/pull/37 and b4d361832844ea773b898d8b454d44dfb276b8ed

This is fixed as well
