### ISSUE TITLE
support for sql server

### ISSUE THREAD

**Issue by mason124124** [Alexis-benoist/eralchemy#73]
Hi, do you support the creation of er diagram directly from the SQL server? I am using SQL server management studio. and manage to make the connection using pyodbc:

conn = pyodbc.connect(
    "Driver={SQL Server Native Client 11.0};"
    "Server=servername;"
    "Database=TEST;"
    "Trusted_Connection=yes;"
)

**Comment by maurerle** [comment]
This should work, as any sqlalchemy compatible engine should work.
If you have a specific issue, just create a new one.
@12rambau could you close this?
