### ISSUE TITLE
Access to push to new branches / create PRs

### ISSUE THREAD

**Issue by louis-vines** [Alexis-benoist/eralchemy#87]
Hi there. I think this tool looks really useful and I'd like to contribute so that it supports [dbml](https://www.dbml.org/home/). However, right now when I try push to the repo I'm getting access denied:

```
$ git push origin fix-tests
ERROR: Permission to Alexis-benoist/eralchemy.git denied to louis-vines.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Can you give me access to contribute to the project?

**Comment by Alexis-benoist** [comment]
Hey,
I added you to the repo. If you can maintain it, that would be great!

**Comment by louis-vines** [comment]
thanks :+1:
