### ISSUE TITLE
Support mermaid markdown

### ISSUE THREAD

**Issue by michaelaltmann** [Alexis-benoist/eralchemy#89]
Now that Github supports rendering mermaid markdown for diagrams (https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/), it would be nice for ERAlchemy to have the option of emitting mermaid-flavored markdown.

**Comment by maurerle** [comment]
This is now also possible: https://github.com/maurerle/eralchemy2/issues/6

For example using `eralchemy2 -i 'markdown_file.er' -o erd_from_markdown_file.md -m mermaid_er`
